### ISSUE TITLE
强推Picgo插件

### ISSUE THREAD

**Issue by huanngzh** [BFlameSwift/img#1]
如果用vscode编辑器，可以在vscode上安装Picgo插件，把Github图床配置一下，之后使用Ctrl+Alt+U快捷键即可在markdown中上传图片至图床，并且会自动在markdown文档中出现链接。
强烈推荐！！！

**Comment by BFlameSwift** [comment]
感谢！！!！！！！
我一般用Typora写hhh，我刚搜了一下发现Typora也支持Picgo，下午软工课可以把两个都配一下[旺柴]
方便多了

**Comment by BFlameSwift** [comment]
终于弄完了[旺柴]，昨天成功了一次，后来退出之后又失败了。。刚才弄好。。
